---
title: "Identificación de genes que intervienen en la patogénesis del síndrome de Turner"
author: "Félix Francisco Enríquez Romero"
date: "20/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INDICE
[1.Abstract](#abstract)

[2.Objetivos](#objetivos)

[3.Materiales y métodos](#matmet)

[3.1.Naturaleza de los datos, tipo de experimento, diseño experimental y tipo de microarrays utilizados](#datos)
  
[3.2.Métodos utilizados en el análisis (Pipeline)](#pipeline)
  
[3.3.Descripción cualitativa de cada paso](#steps)

[4.Resultados del análisis](#resultados)

[5.Discusión](#dicusion)

[6.Apéndice](#apendice)




## 1.Abstract {#abstract}

## 2.Objetivos {#objetivos}

## 3.Materiales y métodos {#matmet}

## 3.1.Naturaleza de los datos, tipo de experimento, diseño experimental y tipo de microarrays utilizados {#datos}

## 3.2.Métodos utilizados en el análisis (Pipeline) {#pipeline}

## 3.3.Descripción cualitativa de cada paso {#steps}

## 4.Resultados del análisis {#resultados}

## 5.Discusión {#dicusion}

## 6.Apéndice {#apendice}

```{r imports, message=FALSE}
if (!(require(stringr))) install.packages("stringr")
if (!(require(tm))) install.packages("tm")
if (!(require(BiocManager))) install.packages("BiocManager")
if (!require(affy))BiocManager::install("affy")
if (!require(affycoretools))BiocManager::install("affycoretools")
if (!require(genefilter))BiocManager::install("genefilter")


if (!(require(hgu133plus2.db)))BiocManager::install("hgu133plus2.db")
if (!require(Biobase))BiocManager::install("Biobase")
if (!require(simpleaffy))BiocManager::install("simpleaffy")
if (!require(affyPLM))BiocManager::install("affyPLM")
```

```{r load}
#library(Biobase)
#library(affy)
library(tm)

# Directorios
workingDir <- getwd()
rawDataDir <- file.path(workingDir, "raw_data")
resultsDir <- file.path(workingDir, "results")

# Función para elegir muestras aleatoriamente
selectSamples<- function (myID){
 set.seed(myID)
 selected <- c(sample(1:10, 6),11, sample(12:26, 5), sample(27:36,6))
 selected <- sort(selected)
}

# Seleccionamos las muestras y almacenamos el nombre de los archivos .CEL
mySelected <- selectSamples(49044820)
targetsAll <- read.csv(file="targetsAll.csv", row.names = 1, head=TRUE)
myTargets <- targetsAll[mySelected,]
fileNames <- row.names(myTargets)

# Obtenemos el nombre completo de los archivos .CEL
all_files <- list.files("raw_data/", pattern = "*.CEL.gz", full.names = FALSE) # Todos
selectFiles <- c() # Los que se necesitan
for(i in 1:length(all_files)){
  fullName = all_files[i]
  name = unlist(strsplit(fullName,"_"))[1] 
  if(is.element(name,fileNames)){ # Si el nombre está en nuestro listado entonces lo añadimos
    selectFiles <- c(selectFiles,fullName)
  }
}

# Modificamos la columna karyotype para que no contenga números
myTargets$karyotype <- removeNumbers(myTargets$karyotype)

# Por último leemos los archivos .CEL que nos interesa y creamos un objeto de tipo AffyBatch
rawData <- read.affybatch(filenames = file.path(rawDataDir,selectFiles),phenoData=AnnotatedDataFrame(myTargets))

# Para tener unos nombres más intuitivos
myTargets$title -> colnames(exprs(rawData))
```

```{r qcRaw}
#library(simpleaffy)
#library(affyPLM)

png(file=paste0(resultsDir,'/boxplot_qcRaw.png'))
# Diagrama de cajas para obtener una idea de las distribución de las intensidades de las distintas muestras
boxplot(rawData, cex.axis=0.8, las=2, col=c(rep("red", 6), rep("blue", 6), rep("green", 6)),main="Distribución de los valores de intensidad en crudo")

png(file=paste0(resultsDir,'/hist_qcRaw.png'))
# Histograma para conocer si las distribuciones de los distintos arrays son similares
hist(rawData, main="Distribución de las señales")

# Hacemos Anális de Comonentes Principales (PCA)
PCA_s <- prcomp(t(exprs(rawData)))
png(file=paste0(resultsDir,'/pca_qcRaw.png'))
plot(PCA_s$x[, 1:2],pch=18, col="blue",main="PCA sobre los datos en crudo")
text(PCA_s$x[, 1:2], row.names(PCA_s$x), cex=0.7, pos=4, offset = 0,col="red")

# Control de calidad en crudo
qualityAnalysisRaw <- qc(rawData)
png(file=paste0(resultsDir,'/qc_statsRaw.png'))
plot(qualityAnalysisRaw)
```

```{r norm}
# Normalización
processedData <- affy::rma(rawData)

# Para tener unos nombres más intuitivos
colnames(processedData) <- myTargets$title

# Guardar
write.csv(exprs(processedData), file=paste0(resultsDir,'/normalized.Data.csv'))
```

```{r filtro}
# COMENTAR
library(genefilter)
library(hgu133plus2.db)
annotation(processedData) <- "hgu133plus2.db"

filtered <- nsFilter(processedData, require.entrez = TRUE, remove.dupEntrez = TRUE, var.filter=TRUE, var.func=IQR, var.cutoff=0.75, filterByQuantile=TRUE, feature.exclude = "^AFFX")

pro_filt_data <-filtered$eset

# Guardar
write.csv(exprs(pro_filt_data), file=paste0(resultsDir,'/normalized.Filtered.Data.csv'))
```

```{r gde}
library(limma)
library(stringr)
# 1 Factor de 3 niveles: XX, Xm, Xp-->Matriz de diseño
grupo <- as.factor(myTargets$karyotype)
designMatrix <- model.matrix(~0 + grupo)
colnames(designMatrix) <- str_replace_all(colnames(designMatrix), "grupo","")

# Contrastar Xm vs Xp y Xm+Xp vs XX
# Ver las diferencias entre las pacientes con TS
# Ver las diferencias entre las pacientes con TS y las pacientes sanas
contMatrix <- makeContrasts(XmvsXp = Xm - Xp, XXvsX_ = XX - ((Xp+Xm)/2),levels=designMatrix)
contMatrix

fit<-lmFit(processedData, designMatrix)
fit.main<-contrasts.fit(fit, contMatrix)
fit.main<-eBayes(fit.main)
class(fit.main)

# Ahora toca obtener las listas de GDEs
#WT.with.no.Fe <- topTable(contrast.results, number=22810,coef=1,sort.by="logFC")
topTab_XmvsXp <- topTable (fit.main, number=nrow(fit.main), coef="XmvsXp", adjust="fdr") 
topTab_XXvsX_ <- topTable (fit.main, number=nrow(fit.main), coef="XXvsX_", adjust="fdr")
head(topTab_XmvsXp)
head(topTab_XXvsX_)


# Visualización rápida
volcanoplot(fit.main, coef=2, highlight=10, names=fit.main$ID, 
             main=paste("Differentially expressed genes", colnames(contMatrix)[2], sep="\n"))
abline(v=c(-1,1))
```

```{r ??}
# Cluster jerarquico
plot(hclust(dist(t(exprs(rawData))),method = "average"))

# Los grupos presentes en el experimento son
#unique(myTargets['karyotype'])

# Tipo de placa
#cdfName(rawData)
image(rawData[,1],col=rainbow(100))
```

```{r anotacion}
library(hgu133plus2.db)
#library(annaffy)
#topTab_XmvsXp_anno <- aafTableAnn(topTab_XmvsXp, hgu133plus2.db, aaf.handler())
library(affycoretools)
#test <- annotateEset(topTab_XmvsXp, hgu133plus2.db)


annotatedTopTable <- function(topTab, anotPackage){
  topTab <- cbind(PROBEID=rownames(topTab), topTab)
  myProbes <- rownames(topTab)
  thePackage <- eval(parse(text = anotPackage))
  geneAnots <- select(thePackage, myProbes, c("SYMBOL", "ENTREZID", "GENENAME"))
  annotatedTopTab<- merge(x=geneAnots, y=topTab, by.x="PROBEID", by.y="PROBEID")
  return(annotatedTopTab)}

topTab_XmvsXp_anno <- annotatedTopTable(topTab_XmvsXp, anotPackage="hgu133plus2.db")
topTab_XXvsX_anno <- annotatedTopTable(topTab_XXvsX_, anotPackage="hgu133plus2.db")


geneSymbols <- select(hgu133plus2.db, rownames(fit.main), c("SYMBOL"))
SYMBOLS<- geneSymbols$SYMBOL
volcanoplot(fit.main, coef=1, highlight=10, names=SYMBOLS, main=paste("Differentially expressed genes", colnames(contMatrix)[1], sep="\n"))
abline(v=c(-1,1))
```

```{r comp_mult}
library(limma)
res<-decideTests(fit.main, method="separate", adjust.method="fdr", p.value=0.05, lfc=1)

sum.res.rows<-apply(abs(res),1,sum)
res.selected<-res[sum.res.rows!=0,] 
print(summary(res))

vennDiagram (res.selected[,1:2], cex=0.9)
title("Genes in common between the three comparisons\n Genes selected with FDR < 0.1 and logFC > 1")


#MAPAS de calor....
```

```{r signicacion}
library(limma)
res<-decideTests(fit.main, method="separate", adjust.method="fdr", p.value=0.05, lfc=1)

sum.res.rows<-apply(abs(res),1,sum)
res.selected<-res[sum.res.rows!=0,] 
print(summary(res))

vennDiagram (res.selected[,1:2], cex=0.9)
title("Genes in common between the three comparisons\n Genes selected with FDR < 0.1 and logFC > 1")


#MAPAS de calor....
```